public enum audioTrack
{
    MUSIC,
    AMBIENT_INDUSTRIAL,
    AMBIENT_NATURE,
    AMBIENT_WEATHER,

    SFX_UI_CLICK,
    SFX_UI_HOVER,

    SFX_INTERACTION_START,
    SFX_INTERACTION_CONTINUE,
    SFX_INTERACTION_END,

    SFX_PLAYER_WALKING,

    SFX_EXTRA_MACHINES,
    SFX_EXTRA_HUMANS,
    SFX_EXTRA_MONSTERS
}
